# Generated by Django 5.1.5 on 2025-06-10 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'fontes',
                'db_table': 'fonte',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'locais',
                'db_table': 'local',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'programas',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('cod_documento', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Cód Doc.')),
                ('num_fita', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_midia', models.CharField(choices=[('vivo', 'Vivo'), ('bruta', 'Bruta'), ('editada', 'Editada')], default='bruta', max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='medias/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome Original do Arquivo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('duracao', models.CharField(blank=True, max_length=20, null=True)),
                ('timecode', models.CharField(blank=True, max_length=20, null=True)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('armazenamento', models.CharField(blank=True, choices=[('disco', 'Disco'), ('local', 'Local'), ('nuvem', 'Nuvem')], max_length=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_fonte', models.ForeignKey(blank=True, db_column='id_fonte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.fonte')),
                ('id_local', models.ForeignKey(blank=True, db_column='id_local', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.local')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('id_programa', models.ForeignKey(blank=True, db_column='id_programa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.programa')),
            ],
            options={
                'verbose_name_plural': 'mídias',
                'db_table': 'midias',
                'ordering': ['-data_cadastro'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resumo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('id_midia', models.OneToOneField(db_column='id_midia', on_delete=django.db.models.deletion.CASCADE, to='medias.midia')),
            ],
            options={
                'db_table': 'resumos',
                'managed': True,
            },
        ),
    ]
