# Generated by Django 5.1.5 on 2025-06-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fonte',
            options={'managed': True, 'ordering': ['nome'], 'verbose_name_plural': 'fontes'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'managed': True, 'ordering': ['nome'], 'verbose_name_plural': 'locais'},
        ),
        migrations.RenameField(
            model_name='fonte',
            old_name='fonte',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='local',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='fonte',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='fonte',
            name='descricao',
        ),
    ]
