# Generated by Django 5.1.5 on 2025-06-10 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('cod_vocabulario', models.IntegerField(primary_key=True, serialize=False)),
                ('termo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vocabulario',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='programa',
            table='programa',
        ),
        migrations.CreateModel(
            name='Sinonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_use', models.CharField(max_length=50)),
                ('cod_sinonimo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referenciado_como_sinonimo', to='medias.vocabulario')),
                ('cod_vocabulario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sinonimos', to='medias.vocabulario')),
            ],
            options={
                'db_table': 'sinonimos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MidiaVocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_midia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medias.midia')),
                ('cod_vocabulario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medias.vocabulario')),
            ],
            options={
                'db_table': 'midias_vocabulario',
                'managed': True,
                'unique_together': {('cod_midia', 'cod_vocabulario')},
            },
        ),
    ]
