# Generated by Django 5.1.5 on 2025-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='cod_documento',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Cód Doc.'),
        ),
    ]
