# Generated by Django 5.1.5 on 2025-06-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_midia_cod_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='data_criacao',
        ),
    ]
