# Generated by Django 5.1.5 on 2025-06-25 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_remove_local_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original do Arquivo'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='tipo_midia',
            field=models.CharField(blank=True, choices=[('vivo', 'Vivo'), ('bruta', 'Bruta'), ('editada', 'Editada')], default='bruta', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
