# Generated by Django 5.1.5 on 2025-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_alter_midia_nome_original_alter_midia_tipo_midia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
