# Generated by Django 5.1.5 on 2025-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_alter_midia_data_alteracao_alter_midia_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
