# Generated by Django 5.1.5 on 2025-06-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0006_alter_resumo_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='cod_documento',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cód Doc.'),
        ),
        migrations.AlterField(
            model_name='resumo',
            name='id_midia',
            field=models.OneToOneField(db_column='id_midia', on_delete=django.db.models.deletion.CASCADE, related_name='resumo', to='medias.midia'),
        ),
    ]
